# Workflow for Node.js CI
name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      node-version: ${{ matrix.node-version }}
