
# Simple workflow that runs on every push to the main branch
name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Say hello
        run: echo "Hello, World!"
